# Site settings
title: TaoKeğŸ˜€
SEOTitle: æ¬¢è¿æ¥åˆ°taokeçš„åšå®¢
header-img: img/girl.jpg
email: 2552744904@qq.com
description: "é…¸ç”œè‹¦è¾£çš„ç”Ÿæ´»ï¼Œæ°¸ä¸åœæ­¢çš„å­¦ä¹ ï¼ŒæœŸå¾…è¯—å’Œè¿œæ–¹ä»¥åŠç”Ÿå‘½ä¸­çš„é‚£ä¸ªå¥¹"
keyword: "taoke, é€ƒè¯¾, é€ƒè¯¾çš„åšå®¢, é™¶å…‹, å‰ç«¯, ç”Ÿæ´», å­¦ä¹ , ç”œç”œçš„ï¼Œæ‹çˆ±ï¼Œå¥¹,shaocong,yangshaocong,å°‘èªï¼Œæ¨å°‘èª"
url: "http://shaocongw.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/ShaoCongw/ShaoCongw.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "æƒ³è¦ç”œç”œçš„æ‹çˆ±å’Œè¿›å¤§å‚"
sidebar-avatar: img/avatar_me_black.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     chang-shou-liang-liang-52
github_username:    kiritoj
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# è¯„è®ºç³»ç»Ÿ
# Disqusï¼ˆhttps://disqus.com/ï¼‰
# disqus_username: shaocongw

# Gitalk
gitalk:
  enable: true    #æ˜¯å¦å¼€å¯Gitalkè¯„è®º
  clientID: 03c3f1327415c6e5f2db                            #ç”Ÿæˆçš„clientID
  clientSecret: 79c110f49a186599ef2b0ed1afe5467f83fbb7bc    #ç”Ÿæˆçš„clientSecret
  repo: ShaoCongw.github.io    #ä»“åº“åç§°
  owner: ShaoCongw    #githubç”¨æˆ·å
  admin: taoke
  distractionFreeMode: true #æ˜¯å¦å¯ç”¨ç±»ä¼¼FBçš„é˜´å½±é®ç½©


# ç»Ÿè®¡

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto               # é»˜è®¤çš„æ˜¯ auto, è¿™é‡Œæˆ‘æ˜¯è‡ªå®šä¹‰äº†çš„åŸŸåï¼Œä½ å¦‚æœæ²¡æœ‰è‡ªå·±çš„åŸŸåï¼Œéœ€è¦æ”¹æˆauto





# Featured Tags
featured-tags: true                     # æ˜¯å¦ä½¿ç”¨é¦–é¡µæ ‡ç­¾
featured-condition-size: 0              # ç›¸åŒæ ‡ç­¾æ•°é‡å¤§äºè¿™ä¸ªæ•°ï¼Œæ‰ä¼šå‡ºç°åœ¨é¦–é¡µ



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "çŸ¥ä¹",
        href: "https://www.zhihu.com/"
    },{
        title: "æ˜é‡‘",
        href: "https://juejin.im/"
    },{
        title: "bilibili",
        href: "https://www.bilibili.com/"
    },{
        title: "Android Developer",
        href: "https://developer.android.google.cn/"
    }
]
